"""Initial tables

Revision ID: 69227f3c3f2a
Revises: 
Create Date: 2025-11-27 23:42:04.375940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69227f3c3f2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poltronas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poltronas_id'), 'poltronas', ['id'], unique=False)
    op.create_table('protocolos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=False),
    sa.Column('restricoes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolos_id'), 'protocolos', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('registro', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('protocolo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_registro'), 'pacientes', ['registro'], unique=True)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('poltrona_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.String(), nullable=False),
    sa.Column('horario_fim', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_farmacia', sa.String(), nullable=True),
    sa.Column('encaixe', sa.Boolean(), nullable=True),
    sa.Column('hora_inicio_real', sa.String(), nullable=True),
    sa.Column('hora_fim_real', sa.String(), nullable=True),
    sa.Column('intercorrencias', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['poltrona_id'], ['poltronas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_index(op.f('ix_agendamentos_status'), 'agendamentos', ['status'], unique=False)
    op.create_table('prescricoes_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.String(), nullable=True),
    sa.Column('medico_nome', sa.String(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('superficie_corporea', sa.Float(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('protocolo_nome', sa.String(), nullable=False),
    sa.Column('numero_ciclo', sa.Integer(), nullable=False),
    sa.Column('dia_ciclo', sa.String(), nullable=True),
    sa.Column('frequencia', sa.String(), nullable=True),
    sa.Column('observacoes_protocolo', sa.Text(), nullable=True),
    sa.Column('pre_qt', sa.JSON(), nullable=True),
    sa.Column('qt', sa.JSON(), nullable=True),
    sa.Column('pos_qt', sa.JSON(), nullable=True),
    sa.Column('tempo_total_infusao', sa.Integer(), nullable=False),
    sa.Column('assinado', sa.Boolean(), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('hora_assinatura', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_medicas_id'), 'prescricoes_medicas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescricoes_medicas_id'), table_name='prescricoes_medicas')
    op.drop_table('prescricoes_medicas')
    op.drop_index(op.f('ix_agendamentos_status'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_pacientes_registro'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_protocolos_id'), table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_poltronas_id'), table_name='poltronas')
    op.drop_table('poltronas')
    # ### end Alembic commands ###
