"""Initial tables

Revision ID: 964352def0d8
Revises: 
Create Date: 2025-12-15 22:19:08.877896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964352def0d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_abertura', sa.String(), nullable=True),
    sa.Column('horario_fechamento', sa.String(), nullable=True),
    sa.Column('dias_funcionamento', sa.JSON(), nullable=True),
    sa.Column('grupos_infusao', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('registro', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('observacoes_clinicas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_pacientes_registro'), 'pacientes', ['registro'], unique=True)
    op.create_table('protocolos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('indicacao', sa.String(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=True),
    sa.Column('numero_ciclos', sa.Integer(), nullable=True),
    sa.Column('grupo_infusao', sa.String(), nullable=True),
    sa.Column('dias_semana_permitidos', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('precaucoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolos_nome'), 'protocolos', ['nome'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.String(), nullable=False),
    sa.Column('horario_fim', sa.String(), nullable=False),
    sa.Column('ciclo_atual', sa.Integer(), nullable=True),
    sa.Column('dia_ciclo', sa.String(), nullable=True),
    sa.Column('encaixe', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_farmacia', sa.String(), nullable=True),
    sa.Column('tempo_estimado_preparo', sa.Integer(), nullable=True),
    sa.Column('horario_previsao_entrega', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_data'), 'agendamentos', ['data'], unique=False)
    op.create_table('contatos_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('parentesco', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_emergencia_id'), 'contatos_emergencia', ['id'], unique=False)
    op.create_table('itens_protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dose_padrao', sa.String(), nullable=True),
    sa.Column('unidade_padrao', sa.String(), nullable=True),
    sa.Column('via_padrao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_protocolo_id'), 'itens_protocolo', ['id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.String(), nullable=True),
    sa.Column('protocolo_id', sa.String(), nullable=True),
    sa.Column('protocolo_nome_snapshot', sa.String(), nullable=True),
    sa.Column('medico_nome', sa.String(), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ciclo_atual', sa.Integer(), nullable=True),
    sa.Column('ciclos_total', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('superficie_corporea', sa.Float(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('via', sa.String(), nullable=True),
    sa.Column('tempo_infusao', sa.Integer(), nullable=True),
    sa.Column('veiculo', sa.String(), nullable=True),
    sa.Column('volume_veiculo', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_prescricao_id'), 'itens_prescricao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_prescricao_id'), table_name='itens_prescricao')
    op.drop_table('itens_prescricao')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_itens_protocolo_id'), table_name='itens_protocolo')
    op.drop_table('itens_protocolo')
    op.drop_index(op.f('ix_contatos_emergencia_id'), table_name='contatos_emergencia')
    op.drop_table('contatos_emergencia')
    op.drop_index(op.f('ix_agendamentos_data'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_protocolos_nome'), table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_pacientes_registro'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
